<a href="https://colab.research.google.com/github/anjalis06-dev/PYDS/blob/main/PYDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy : Numerical Python

Important attributes of Numpy

1. NumPy array is called as **ndarray**
2. **ndarray.ndim**: the no of axes(dimensions) of the arrays
3. **ndarray.shape** : Tuple of integers that gives size of the array in each dimension
for an m n matix, shape is (n,m). the length of the shape of tuple is number of axes, ndim.
4.** ndarray.size**: the total number of elements of the array is equal to the product of the elements of the shape.
5. **ndarray.dtype**: An Object that descibes the type of elements in the array
For exm: numpy.int32, numpy.int16, numpy.float64

6. **ndarray.itemsize**: size in bytes of each element of the array
For exm : elements are float64 then
itemsize= 64/8 = 8
for complex 32, itemsize = 32/8 = 4
 it is denoted by **ndarray.dtype.itemsize**

 7. **ndarray.data** : the buffer contains the actual elements of array. However, for accessing the elements of the array , use indexing and not ndarray.data



*   Arithmetic Operations Using NumPy

1. **np.add** : gives addition of numpy arrays
2. **np.substract**: gives substraction of arrays
3. **np.multiply**: gives multiplication of arrays
4. **np.divide** : gives division
5. **np.power(A,n)** : gives power of n to each element



In [ ]:
#Arithmetic Operations Using NumPy
import numpy as np

In [ ]:
A= np.array([[1,2,1],[2,2,3]])
B= np.array([3,4,5])

In [ ]:
A

array([[1, 2, 1],
       [2, 2, 3]])

In [ ]:
B

array([3, 4, 5])

In [ ]:
np.add(A,B)

array([[4, 6, 6],
       [5, 6, 8]])

In [ ]:
np.subtract(B,A)

array([[2, 2, 4],
       [1, 2, 2]])

In [ ]:
np.multiply(A,B)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

In [ ]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

In [ ]:
np.power(A,3)

array([[ 1,  8,  1],
       [ 8,  8, 27]])

In [ ]:
np.power(A,B)

array([[  1,  16,   1],
       [  8,  16, 243]])

Conditional Handling in Numpy Python
1. **np.where** =  function is a vectorized tool used for conditional operations on arrays.

*  Finding Indices (One Argument)When used with only a condition, np.where(condition) returns a tuple of arrays containing the indices where the condition is True.
* Conditional Replacement (Three Arguments)When used with three arguments, np.where(condition, x, y), it acts like a vectorized if-else statement.


2. **np.select** =  is to perform complex conditional mapping on an array where multiple different outcomes are required based on multiple conditions.


In [ ]:
x = np.array([i for i in range(10)])

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.where(x%2==0,'Even','Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [ ]:
#condition list
condlist = [x<5,x>5]
#choice list
choicelist=[x**2,x**3]

In [ ]:
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

Common Mathematical And Statistical Operations in Numpy

1. **np.amin** = gives minimum value in the array
2. **np.max** = gives max value from array
3. **np.amax** = gives max value acc to axis( horizontal or vertical)

In [ ]:
arr = np.array([[4,3,2],[10,1,0],[5,8,24]])

In [ ]:
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [ ]:
np.amin(arr)

np.int64(0)

In [ ]:
np.amin(arr,axis=1) # 1 vertical 0 horizontal

array([2, 0, 5])

In [ ]:
np.max(arr)

np.int64(24)

In [ ]:
np.amax(arr,axis=1)

array([ 4, 10, 24])

In [ ]:
np.median(arr)

np.float64(4.0)

In [ ]:
np.mean(arr)

np.float64(6.333333333333333)

In [ ]:
np.std(arr)

np.float64(6.944222218666553)

In [ ]:
np.var(arr)

np.float64(48.22222222222222)

In [ ]:
np.percentile(arr,50) #return value that is at 50 percentile

np.float64(4.0)

In [ ]:
deg = np.array([0,30,45,60,90])

In [ ]:
np.sin(deg*np.pi/180)#convert deg into radian for inverse angles use arcsin, arccos, arctan

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [ ]:
np.cos(deg*np.pi/180)#convert deg into radian

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [ ]:
np.tan(deg*np.pi/180)#convert deg into radian

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [ ]:
'''for inverse angles use arcsin, arccos, arctan'''


'for inverse angles use arcsin, arccos, arctan'

In [ ]:
arr = np.array([0.1,0.8,-2.2,-9.87])

In [ ]:
np.floor(arr)

array([  0.,   0.,  -3., -10.])

In [ ]:
np.ceil(arr)

array([ 1.,  1., -2., -9.])

**Linear Algebra**:

In [ ]:
def dt_product(x,y):
  return sum(i*j for i,j in zip(x,y,strict=True))

In [ ]:
dt_product([1,5,7],[8,9,6])

95

In [ ]:
#norm of vector == length of vector
import math
def norm_of_vector(v):
  dot_product= sum(i*i for i in v)
  return math.sqrt(dot_product)
norm_of_vector([8,9,6])

13.45362404707371

**Statistics**

Population
Sample: sample is subset of population
measurement: no or attribute for each member of population or sample data
Parameter: characteristics of population that we estimate or track
statistics : char of sample usually helps to extimate or test population parameter ex: mean
variable : something that can take on diff value in data set